apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: appconfig
spec:
  metadata:
    - name: redisHost
      value: "localhost:6379"
    - name: redisPassword
      value: ""
  backend:
    type: redis
    metadata:
      - name: redisHost
        value: "localhost:6379"
